// Hand-curated public-cloud region coordinates. Sources: AWS, Azure, GCP
// region documentation pages (publicly published). Coordinates are the
// city center of the named region (datacenter exact locations are typically
// undisclosed). Last refreshed: 2026-05.

export type CloudProvider = 'AWS' | 'Azure' | 'GCP';

export const CLOUD_COLORS: Record<CloudProvider, string> = {
  AWS:   '#ff9900',
  Azure: '#00a4ef',
  GCP:   '#4285f4',
};

export interface CloudRegion {
  provider: CloudProvider;
  code: string;
  name: string;
  lat: number;
  lng: number;
}

export const CLOUD_REGIONS: CloudRegion[] = [
  // ── AWS ──────────────────────────────────────────────────────────────────
  { provider: 'AWS', code: 'us-east-1',      name: 'N. Virginia',   lat: 38.13,  lng: -78.45 },
  { provider: 'AWS', code: 'us-east-2',      name: 'Ohio',          lat: 39.96,  lng: -83.00 },
  { provider: 'AWS', code: 'us-west-1',      name: 'N. California', lat: 37.35,  lng: -121.96 },
  { provider: 'AWS', code: 'us-west-2',      name: 'Oregon',        lat: 45.87,  lng: -119.69 },
  { provider: 'AWS', code: 'ca-central-1',   name: 'Montreal',      lat: 45.50,  lng: -73.57 },
  { provider: 'AWS', code: 'ca-west-1',      name: 'Calgary',       lat: 51.04,  lng: -114.07 },
  { provider: 'AWS', code: 'sa-east-1',      name: 'São Paulo',     lat: -23.55, lng: -46.63 },
  { provider: 'AWS', code: 'eu-west-1',      name: 'Ireland',       lat: 53.34,  lng: -6.26 },
  { provider: 'AWS', code: 'eu-west-2',      name: 'London',        lat: 51.50,  lng: -0.12 },
  { provider: 'AWS', code: 'eu-west-3',      name: 'Paris',         lat: 48.85,  lng: 2.35 },
  { provider: 'AWS', code: 'eu-central-1',   name: 'Frankfurt',     lat: 50.11,  lng: 8.68 },
  { provider: 'AWS', code: 'eu-central-2',   name: 'Zurich',        lat: 47.37,  lng: 8.55 },
  { provider: 'AWS', code: 'eu-north-1',     name: 'Stockholm',     lat: 59.33,  lng: 18.07 },
  { provider: 'AWS', code: 'eu-south-1',     name: 'Milan',         lat: 45.46,  lng: 9.19 },
  { provider: 'AWS', code: 'eu-south-2',     name: 'Spain',         lat: 40.42,  lng: -3.70 },
  { provider: 'AWS', code: 'ap-northeast-1', name: 'Tokyo',         lat: 35.69,  lng: 139.69 },
  { provider: 'AWS', code: 'ap-northeast-2', name: 'Seoul',         lat: 37.57,  lng: 126.98 },
  { provider: 'AWS', code: 'ap-northeast-3', name: 'Osaka',         lat: 34.69,  lng: 135.50 },
  { provider: 'AWS', code: 'ap-southeast-1', name: 'Singapore',     lat: 1.35,   lng: 103.82 },
  { provider: 'AWS', code: 'ap-southeast-2', name: 'Sydney',        lat: -33.87, lng: 151.21 },
  { provider: 'AWS', code: 'ap-southeast-3', name: 'Jakarta',       lat: -6.21,  lng: 106.85 },
  { provider: 'AWS', code: 'ap-southeast-4', name: 'Melbourne',     lat: -37.81, lng: 144.96 },
  { provider: 'AWS', code: 'ap-southeast-5', name: 'Malaysia',      lat: 3.14,   lng: 101.69 },
  { provider: 'AWS', code: 'ap-south-1',     name: 'Mumbai',        lat: 19.07,  lng: 72.88 },
  { provider: 'AWS', code: 'ap-south-2',     name: 'Hyderabad',     lat: 17.38,  lng: 78.49 },
  { provider: 'AWS', code: 'ap-east-1',      name: 'Hong Kong',     lat: 22.32,  lng: 114.17 },
  { provider: 'AWS', code: 'me-south-1',     name: 'Bahrain',       lat: 26.07,  lng: 50.55 },
  { provider: 'AWS', code: 'me-central-1',   name: 'UAE',           lat: 24.47,  lng: 54.37 },
  { provider: 'AWS', code: 'il-central-1',   name: 'Tel Aviv',      lat: 32.08,  lng: 34.78 },
  { provider: 'AWS', code: 'af-south-1',     name: 'Cape Town',     lat: -33.92, lng: 18.42 },

  // ── Microsoft Azure ──────────────────────────────────────────────────────
  { provider: 'Azure', code: 'eastus',              name: 'Virginia',     lat: 37.43,  lng: -78.66 },
  { provider: 'Azure', code: 'eastus2',             name: 'Virginia 2',   lat: 36.85,  lng: -76.30 },
  { provider: 'Azure', code: 'centralus',           name: 'Iowa',         lat: 41.59,  lng: -93.62 },
  { provider: 'Azure', code: 'northcentralus',      name: 'Illinois',     lat: 41.88,  lng: -87.63 },
  { provider: 'Azure', code: 'southcentralus',      name: 'Texas',        lat: 29.42,  lng: -98.49 },
  { provider: 'Azure', code: 'westus',              name: 'California',   lat: 37.78,  lng: -122.42 },
  { provider: 'Azure', code: 'westus2',             name: 'Washington',   lat: 47.23,  lng: -119.85 },
  { provider: 'Azure', code: 'westus3',             name: 'Phoenix',      lat: 33.45,  lng: -112.07 },
  { provider: 'Azure', code: 'canadacentral',       name: 'Toronto',      lat: 43.65,  lng: -79.38 },
  { provider: 'Azure', code: 'canadaeast',          name: 'Quebec City',  lat: 46.81,  lng: -71.21 },
  { provider: 'Azure', code: 'brazilsouth',         name: 'São Paulo',    lat: -23.55, lng: -46.63 },
  { provider: 'Azure', code: 'northeurope',         name: 'Ireland',      lat: 53.34,  lng: -6.26 },
  { provider: 'Azure', code: 'westeurope',          name: 'Netherlands',  lat: 52.37,  lng: 4.90 },
  { provider: 'Azure', code: 'uksouth',             name: 'London',       lat: 50.94,  lng: -0.80 },
  { provider: 'Azure', code: 'ukwest',              name: 'Cardiff',      lat: 51.48,  lng: -3.18 },
  { provider: 'Azure', code: 'francecentral',       name: 'Paris',        lat: 46.36,  lng: 2.37 },
  { provider: 'Azure', code: 'germanywestcentral',  name: 'Frankfurt',    lat: 50.11,  lng: 8.68 },
  { provider: 'Azure', code: 'switzerlandnorth',    name: 'Zurich',       lat: 47.37,  lng: 8.55 },
  { provider: 'Azure', code: 'norwayeast',          name: 'Oslo',         lat: 59.91,  lng: 10.75 },
  { provider: 'Azure', code: 'swedencentral',       name: 'Gävle',        lat: 60.67,  lng: 17.14 },
  { provider: 'Azure', code: 'polandcentral',       name: 'Warsaw',       lat: 52.23,  lng: 21.01 },
  { provider: 'Azure', code: 'italynorth',          name: 'Milan',        lat: 45.46,  lng: 9.19 },
  { provider: 'Azure', code: 'spaincentral',        name: 'Madrid',       lat: 40.42,  lng: -3.70 },
  { provider: 'Azure', code: 'southeastasia',       name: 'Singapore',    lat: 1.35,   lng: 103.82 },
  { provider: 'Azure', code: 'eastasia',            name: 'Hong Kong',    lat: 22.32,  lng: 114.17 },
  { provider: 'Azure', code: 'japaneast',           name: 'Tokyo',        lat: 35.68,  lng: 139.77 },
  { provider: 'Azure', code: 'japanwest',           name: 'Osaka',        lat: 34.69,  lng: 135.50 },
  { provider: 'Azure', code: 'koreacentral',        name: 'Seoul',        lat: 37.57,  lng: 126.98 },
  { provider: 'Azure', code: 'australiaeast',       name: 'Sydney',       lat: -33.87, lng: 151.21 },
  { provider: 'Azure', code: 'australiasoutheast',  name: 'Melbourne',    lat: -37.81, lng: 144.96 },
  { provider: 'Azure', code: 'centralindia',        name: 'Pune',         lat: 18.52,  lng: 73.86 },
  { provider: 'Azure', code: 'southindia',          name: 'Chennai',      lat: 13.08,  lng: 80.27 },
  { provider: 'Azure', code: 'westindia',           name: 'Mumbai',       lat: 19.07,  lng: 72.88 },
  { provider: 'Azure', code: 'uaenorth',            name: 'Dubai',        lat: 25.20,  lng: 55.27 },
  { provider: 'Azure', code: 'qatarcentral',        name: 'Doha',         lat: 25.29,  lng: 51.53 },
  { provider: 'Azure', code: 'israelcentral',       name: 'Tel Aviv',     lat: 32.08,  lng: 34.78 },
  { provider: 'Azure', code: 'southafricanorth',    name: 'Johannesburg', lat: -26.20, lng: 28.05 },

  // ── Google Cloud ─────────────────────────────────────────────────────────
  { provider: 'GCP', code: 'us-central1',        name: 'Iowa',          lat: 41.59,  lng: -93.62 },
  { provider: 'GCP', code: 'us-east1',           name: 'S. Carolina',   lat: 33.84,  lng: -81.16 },
  { provider: 'GCP', code: 'us-east4',           name: 'N. Virginia',   lat: 39.04,  lng: -77.49 },
  { provider: 'GCP', code: 'us-east5',           name: 'Columbus',      lat: 39.96,  lng: -83.00 },
  { provider: 'GCP', code: 'us-south1',          name: 'Dallas',        lat: 32.78,  lng: -96.80 },
  { provider: 'GCP', code: 'us-west1',           name: 'Oregon',        lat: 45.60,  lng: -121.18 },
  { provider: 'GCP', code: 'us-west2',           name: 'Los Angeles',   lat: 34.05,  lng: -118.24 },
  { provider: 'GCP', code: 'us-west3',           name: 'Salt Lake City',lat: 40.76,  lng: -111.89 },
  { provider: 'GCP', code: 'us-west4',           name: 'Las Vegas',     lat: 36.17,  lng: -115.14 },
  { provider: 'GCP', code: 'northamerica-northeast1', name: 'Montréal', lat: 45.50,  lng: -73.57 },
  { provider: 'GCP', code: 'northamerica-northeast2', name: 'Toronto',  lat: 43.65,  lng: -79.38 },
  { provider: 'GCP', code: 'southamerica-east1', name: 'São Paulo',     lat: -23.55, lng: -46.63 },
  { provider: 'GCP', code: 'southamerica-west1', name: 'Santiago',      lat: -33.45, lng: -70.67 },
  { provider: 'GCP', code: 'europe-west1',       name: 'Belgium',       lat: 50.45,  lng: 4.36 },
  { provider: 'GCP', code: 'europe-west2',       name: 'London',        lat: 51.50,  lng: -0.12 },
  { provider: 'GCP', code: 'europe-west3',       name: 'Frankfurt',     lat: 50.11,  lng: 8.68 },
  { provider: 'GCP', code: 'europe-west4',       name: 'Netherlands',   lat: 53.44,  lng: 6.84 },
  { provider: 'GCP', code: 'europe-west6',       name: 'Zurich',        lat: 47.37,  lng: 8.55 },
  { provider: 'GCP', code: 'europe-west8',       name: 'Milan',         lat: 45.46,  lng: 9.19 },
  { provider: 'GCP', code: 'europe-west9',       name: 'Paris',         lat: 48.85,  lng: 2.35 },
  { provider: 'GCP', code: 'europe-west10',      name: 'Berlin',        lat: 52.52,  lng: 13.40 },
  { provider: 'GCP', code: 'europe-west12',      name: 'Turin',         lat: 45.07,  lng: 7.69 },
  { provider: 'GCP', code: 'europe-north1',      name: 'Finland',       lat: 60.57,  lng: 27.19 },
  { provider: 'GCP', code: 'europe-southwest1',  name: 'Madrid',        lat: 40.42,  lng: -3.70 },
  { provider: 'GCP', code: 'europe-central2',    name: 'Warsaw',        lat: 52.23,  lng: 21.01 },
  { provider: 'GCP', code: 'asia-east1',         name: 'Taiwan',        lat: 24.05,  lng: 120.51 },
  { provider: 'GCP', code: 'asia-east2',         name: 'Hong Kong',     lat: 22.32,  lng: 114.17 },
  { provider: 'GCP', code: 'asia-northeast1',    name: 'Tokyo',         lat: 35.68,  lng: 139.77 },
  { provider: 'GCP', code: 'asia-northeast2',    name: 'Osaka',         lat: 34.69,  lng: 135.50 },
  { provider: 'GCP', code: 'asia-northeast3',    name: 'Seoul',         lat: 37.57,  lng: 126.98 },
  { provider: 'GCP', code: 'asia-southeast1',    name: 'Singapore',     lat: 1.35,   lng: 103.82 },
  { provider: 'GCP', code: 'asia-southeast2',    name: 'Jakarta',       lat: -6.21,  lng: 106.85 },
  { provider: 'GCP', code: 'asia-south1',        name: 'Mumbai',        lat: 19.07,  lng: 72.88 },
  { provider: 'GCP', code: 'asia-south2',        name: 'Delhi',         lat: 28.61,  lng: 77.21 },
  { provider: 'GCP', code: 'australia-southeast1', name: 'Sydney',      lat: -33.87, lng: 151.21 },
  { provider: 'GCP', code: 'australia-southeast2', name: 'Melbourne',   lat: -37.81, lng: 144.96 },
  { provider: 'GCP', code: 'me-central1',        name: 'Doha',          lat: 25.29,  lng: 51.53 },
  { provider: 'GCP', code: 'me-central2',        name: 'Dammam',        lat: 26.39,  lng: 49.98 },
  { provider: 'GCP', code: 'me-west1',           name: 'Tel Aviv',      lat: 32.08,  lng: 34.78 },
  { provider: 'GCP', code: 'africa-south1',      name: 'Johannesburg',  lat: -26.20, lng: 28.05 },
];
